import { Order, DeflectionAnalytics } from './types';

export const INITIAL_ORDERS: Order[] = [
  {
    orderNumber: 'NS1001',
    customerName: 'Sarah Jenkins',
    email: 'sarah.j@example.com',
    orderDate: '2026-08-11',
    status: 'Processing',
    statusMessage: 'Your order is currently being prepared for shipment in our Seattle fulfillment center.',
    shippingAddress: '742 Evergreen Terrace, Seattle, WA 98101',
    total: 129.99,
    items: [
      {
        id: 'item-1',
        name: 'Acoustic Clarity Wireless Headphones',
        price: 129.99,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&auto=format&fit=crop&q=80',
      },
    ],
    returnStatus: 'Eligible',
    returnWindowDays: 30,
  },
  {
    orderNumber: 'NS1002',
    customerName: 'Marcus Vance',
    email: 'marcus.v@example.com',
    orderDate: '2026-08-10',
    status: 'Packed',
    statusMessage: 'Your order has been packed and is waiting to be collected by our carrier partner.',
    carrier: 'FedEx Express',
    shippingAddress: '1204 Pine Street, San Francisco, CA 94109',
    total: 249.50,
    items: [
      {
        id: 'item-2',
        name: 'Ergonomic Mesh Task Desk Chair',
        price: 249.50,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1580481072645-022f9a6d128d?w=400&auto=format&fit=crop&q=80',
      },
    ],
    returnStatus: 'Eligible',
    returnWindowDays: 30,
  },
  {
    orderNumber: 'NS1003',
    customerName: 'Elena Rostova',
    email: 'elena.r@example.com',
    orderDate: '2026-08-08',
    status: 'Shipped',
    statusMessage: 'Your order has been shipped and is on its way. Estimated delivery is within 2-3 business days.',
    trackingNumber: 'TRK-9948201938',
    carrier: 'UPS Ground',
    estimatedDelivery: '2026-08-14',
    shippingAddress: '550 Michigan Ave, Chicago, IL 60611',
    total: 89.00,
    items: [
      {
        id: 'item-3',
        name: 'Tactile Mechanical Gaming Keyboard',
        price: 89.00,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&auto=format&fit=crop&q=80',
      },
    ],
    returnStatus: 'Eligible',
    returnWindowDays: 30,
  },
  {
    orderNumber: 'NS1004',
    customerName: 'David Kim',
    email: 'david.k@example.com',
    orderDate: '2026-08-07',
    status: 'Out for Delivery',
    statusMessage: 'Good news! Your package is currently on the local courier truck and scheduled to arrive today.',
    trackingNumber: 'TRK-8820491022',
    carrier: 'USPS Priority',
    estimatedDelivery: '2026-08-13 (Today)',
    shippingAddress: '88 Austin Blvd, Austin, TX 78701',
    total: 64.50,
    items: [
      {
        id: 'item-4',
        name: 'Minimalist Weatherproof Commuter Backpack',
        price: 64.50,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&auto=format&fit=crop&q=80',
      },
    ],
    returnStatus: 'Eligible',
    returnWindowDays: 30,
  },
  {
    orderNumber: 'NS1005',
    customerName: 'Chloe Bennett',
    email: 'chloe.b@example.com',
    orderDate: '2026-08-01',
    status: 'Delivered',
    statusMessage: 'Delivered on August 4, 2026 to front porch.',
    trackingNumber: 'TRK-7719203941',
    carrier: 'FedEx Express',
    shippingAddress: '312 Beacon St, Boston, MA 02116',
    total: 110.00,
    items: [
      {
        id: 'item-5',
        name: 'Full-Grain Italian Leather Sneakers',
        price: 110.00,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&auto=format&fit=crop&q=80',
      },
    ],
    returnStatus: 'Eligible',
    returnWindowDays: 30,
  },
  {
    orderNumber: 'NS1006',
    customerName: 'Robert Vance',
    email: 'robert.v@example.com',
    orderDate: '2026-06-15',
    status: 'Delivered',
    statusMessage: 'Delivered on June 18, 2026.',
    trackingNumber: 'TRK-1102938491',
    carrier: 'UPS Ground',
    shippingAddress: '404 Oak Lane, Denver, CO 80202',
    total: 199.99,
    items: [
      {
        id: 'item-6',
        name: 'Titanium Smart Health Tracker Watch',
        price: 199.99,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&auto=format&fit=crop&q=80',
      },
    ],
    returnStatus: 'Not Eligible',
    returnReason: 'Order was delivered over 30 days ago (outside 30-day return window).',
    returnWindowDays: 30,
  },
  {
    orderNumber: 'NS1007',
    customerName: 'Jessica Taylor',
    email: 'jessica.t@example.com',
    orderDate: '2026-08-05',
    status: 'Delivered',
    statusMessage: 'Delivered on August 8, 2026.',
    trackingNumber: 'TRK-4491029384',
    carrier: 'FedEx Home',
    shippingAddress: '901 River Road, Portland, OR 97201',
    total: 45.00,
    items: [
      {
        id: 'item-7',
        name: 'Artisan Matte Ceramic Coffee Carafe & Mug Set',
        price: 45.00,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&auto=format&fit=crop&q=80',
      },
    ],
    returnStatus: 'Eligible',
    isDamagedReported: true,
    returnWindowDays: 30,
  },
  {
    orderNumber: 'NS1008',
    customerName: 'Anthony Wright',
    email: 'anthony.w@example.com',
    orderDate: '2026-08-02',
    status: 'Cancelled',
    statusMessage: 'Order was cancelled prior to dispatch per customer request.',
    shippingAddress: '15 Ocean Ave, Miami, FL 33139',
    total: 78.20,
    items: [
      {
        id: 'item-8',
        name: 'Insulated Stainless Steel Hydro Flask',
        price: 78.20,
        quantity: 2,
        image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&auto=format&fit=crop&q=80',
      },
    ],
    returnStatus: 'Not Eligible',
    returnReason: 'Cancelled order.',
    returnWindowDays: 30,
  },
  {
    orderNumber: 'NS1009',
    customerName: 'Amanda Martinez',
    email: 'amanda.m@example.com',
    orderDate: '2026-07-28',
    status: 'Delivered',
    statusMessage: 'Return received at Seattle warehouse. Inspection complete.',
    trackingNumber: 'RET-3301928491',
    shippingAddress: '220 Market St, Philadelphia, PA 19106',
    total: 89.99,
    items: [
      {
        id: 'item-9',
        name: 'Organic Merino Wool Cable Sweater',
        price: 89.99,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&auto=format&fit=crop&q=80',
      },
    ],
    returnStatus: 'Refund Processing',
    refundAmount: 89.99,
    returnWindowDays: 30,
  },
  {
    orderNumber: 'NS1010',
    customerName: 'Daniel Foster',
    email: 'daniel.f@example.com',
    orderDate: '2026-07-20',
    status: 'Delivered',
    statusMessage: 'Returned and refund credited.',
    trackingNumber: 'RET-1192039482',
    shippingAddress: '707 Peachtree St, Atlanta, GA 30308',
    total: 120.00,
    items: [
      {
        id: 'item-10',
        name: 'Active Noise-Isolating Earbuds',
        price: 120.00,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&auto=format&fit=crop&q=80',
      },
    ],
    returnStatus: 'Refund Completed',
    refundAmount: 120.00,
    returnWindowDays: 30,
  },
];

export const INITIAL_ANALYTICS: DeflectionAnalytics = {
  totalConversations: 142,
  deflectedCount: 121,
  escalatedCount: 21,
  deflectionRate: 85.2,
  intentBreakdown: {
    orderStatus: 78,
    returnsRefunds: 43,
    escalated: 21,
  },
  recentTickets: [
    {
      ticketId: 'TKT-9482',
      orderNumber: 'NS1007',
      customerName: 'Jessica Taylor',
      reason: 'Damaged item reported (Ceramic Coffee Carafe)',
      timestamp: '2026-08-13 01:45 AM',
      status: 'Pending',
      conversationSnippet: [
        'Customer: My item NS1007 arrived damaged in transit.',
        'Assistant: I am sorry to hear that. Damaged items require investigation by our specialist team. Connecting you now.',
      ],
    },
    {
      ticketId: 'TKT-9481',
      orderNumber: 'NS1006',
      customerName: 'Robert Vance',
      reason: 'Customer dispute regarding return window expiration',
      timestamp: '2026-08-12 11:20 PM',
      status: 'In Progress',
      conversationSnippet: [
        'Customer: Can I return order NS1006?',
        'Assistant: Unfortunately, this order is no longer eligible for return because it is outside our 30-day window.',
        'Customer: I want to speak to a manager.',
      ],
    },
    {
      ticketId: 'TKT-9480',
      orderNumber: undefined,
      customerName: 'Guest User',
      reason: 'Out of scope request: Payment card discrepancy',
      timestamp: '2026-08-12 09:14 PM',
      status: 'Resolved',
      conversationSnippet: [
        'Customer: Why was my credit card charged twice?',
        'Assistant: I can only assist with Order Status and Returns & Refunds. Connecting you with support.',
      ],
    },
  ],
};
